# This is a Docker Compose configuration for local use.

# Run all services:
# docker compose up --build --wait

services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    restart: no
    depends_on:
      - api
      - redis # Wait for the database to be ready before starting the application
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro" # Read-only settings file
    environment:
      TZ: Europe/Moscow # Set the timezone for correct calendar image generation

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: no
    depends_on:
      db:
        condition: service_healthy
      alembic-migrate:
        condition: service_completed_successfully
    ports:
      - "8001:8000"
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro" # Read-only settings file
    environment:
      TZ: Europe/Moscow # Set the timezone for correct calendar image generation

  alembic-migrate:
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: no
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro" # Read-only settings file
    command: alembic upgrade head

  db:
    # See more: https://hub.docker.com/_/postgres
    image: "postgres:17.1"
    restart: no
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 5s
      start_period: 30s
      interval: 1m
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  redis:
    # See more: https://hub.docker.com/_/redis
    image: "redis:7.2.4-alpine"
    restart: no
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"

volumes:
  postgres:
  redis:
