$schema: "./settings.schema.yaml"
api_settings:
  db_url: "postgresql+asyncpg://postgres:postgres@localhost:5433/postgres"
  bot_token: "some-telegram-bot-token" # get it from @BotFather (same as bot_settings.bot_token)
  api_key: "some-secret-key" # use `openssl rand -hex 32` to generate a random key
bot_settings:
  webhook_url: "http://127.0.0.1:8002" # url of tg-bot webserver
  api_url: "http://127.0.0.1:8001"
  bot_token: "some-telegram-bot-token" # get it from @BotFather
  # redis_url: "redis://127.0.0.1:6379/0" # or delete this line to disable redis and use in-memory storage
accounts:
  # Get from https://api.innohassle.ru/accounts/v0/tokens/generate-service-token?sub=music-room-local-dev&scopes=users&only_for_me=true
  api_jwt_token: "secret"
