$schema: https://json-schema.org/draft-07/schema
$defs:
  Accounts:
    description: InNoHassle-Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0
        title: Api Url
        type: string
      api_jwt_token:
        format: password
        title: Api Jwt Token
        type: string
        writeOnly: true
      telegram_login_url:
        default: https://innohassle.ru/account/connect-telegram
        title: Telegram Login Url
        type: string
      telegram_bot_username:
        default: InNoHassleBot
        title: Telegram Bot Username
        type: string
    required:
    - api_jwt_token
    title: Accounts
    type: object
  ApiSettings:
    properties:
      app_root_path:
        default: ''
        title: App Root Path
        type: string
      cors_allow_origin_regex:
        default: .*
        title: Cors Allow Origin Regex
        type: string
      db_url:
        examples:
        - postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
        - postgresql+asyncpg://postgres:postgres@db:5432/postgres
        title: Db Url
        type: string
      bot_token:
        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        title: Bot Token
        type: string
      bot_webhook_url:
        default: http://127.0.0.1:8002
        title: Bot Webhook Url
        type: string
      api_key:
        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        title: Api Key
        type: string
    required:
    - db_url
    - bot_token
    - api_key
    title: ApiSettings
    type: object
  BotSettings:
    properties:
      environment:
        $ref: '#/$defs/Environment'
        default: development
      bot_token:
        format: password
        title: Bot Token
        type: string
        writeOnly: true
      api_url:
        default: http://127.0.0.1:8001
        title: Api Url
        type: string
      redis_url:
        anyOf:
        - format: password
          type: string
          writeOnly: true
        - type: 'null'
        default: null
        title: Redis Url
      users:
        default: []
        items:
          type: integer
        title: Users
        type: array
      notification_time:
        anyOf:
        - format: time
          type: string
        - type: 'null'
        default: null
        title: Notification Time
    required:
    - bot_token
    title: BotSettings
    type: object
  Environment:
    enum:
    - development
    - production
    - staging
    title: Environment
    type: string
properties:
  api_settings:
    anyOf:
    - $ref: '#/$defs/ApiSettings'
    - type: 'null'
    default: null
  bot_settings:
    anyOf:
    - $ref: '#/$defs/BotSettings'
    - type: 'null'
    default: null
  accounts:
    anyOf:
    - $ref: '#/$defs/Accounts'
    - type: 'null'
    default: null
title: Settings
type: object
