$schema: "./settings.schema.yaml"
api_settings:
  db_url: null
  bot_token: null # get it from @BotFather (same as bot_settings.bot_token)
  api_key: null # use `openssl rand -hex 32` to generate a random key
bot_settings:
  bot_token: null # get it from @BotFather
accounts:
  # Get from https://api.innohassle.ru/accounts/v0/tokens/generate-service-token?sub=music-room-local-dev&scopes=users&only_for_me=true
  api_jwt_token: null
