$schema: https://json-schema.org/draft-07/schema
$defs:
  Accounts:
    description: InNoHassle-Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0
        title: Api Url
        type: string
      api_jwt_token:
        format: password
        title: Api Jwt Token
        type: string
        writeOnly: true
      telegram_login_url:
        default: https://innohassle.ru/account/connect-telegram
        title: Telegram Login Url
        type: string
      telegram_bot_username:
        default: InNoHassleBot
        title: Telegram Bot Username
        type: string
    required:
    - api_jwt_token
    title: Accounts
    type: object
  ApiSettings:
    properties:
      app_root_path:
        default: ''
        description: Prefix for the API path (e.g. "/api/v0")
        title: App Root Path
        type: string
      db_url:
        default: postgresql+asyncpg://postgres:postgres@localhost:5433/postgres
        example: postgresql+asyncpg://user:password@localhost:5433/db_name
        title: Db Url
        type: string
      bot_token:
        description: Bot token from @BotFather
        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        title: Bot Token
        type: string
      api_key:
        description: API key for access to the Music Room API
        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        title: Api Key
        type: string
    required:
    - bot_token
    - api_key
    title: ApiSettings
    type: object
  BotSettings:
    properties:
      environment:
        $ref: '#/$defs/Environment'
        default: development
      bot_token:
        description: Bot token from @BotFather
        format: password
        title: Bot Token
        type: string
        writeOnly: true
      api_url:
        title: Api Url
        type: string
      redis_url:
        anyOf:
        - format: password
          type: string
          writeOnly: true
        - type: 'null'
        default: null
        title: Redis Url
      users:
        default: []
        items:
          type: integer
        title: Users
        type: array
      notification_time:
        anyOf:
        - format: time
          type: string
        - type: 'null'
        default: null
        description: According to UTC
        title: Notification Time
    required:
    - bot_token
    - api_url
    title: BotSettings
    type: object
  Environment:
    enum:
    - development
    - production
    - staging
    title: Environment
    type: string
properties:
  api_settings:
    anyOf:
    - $ref: '#/$defs/ApiSettings'
    - type: 'null'
    default: null
  bot_settings:
    anyOf:
    - $ref: '#/$defs/BotSettings'
    - type: 'null'
    default: null
  accounts:
    anyOf:
    - $ref: '#/$defs/Accounts'
    - type: 'null'
    default: null
title: Settings
type: object
