"""make telegram id bigint

Revision ID: 470fe3126fc0
Revises: 440853283436
Create Date: 2024-09-28 19:46:45.731020

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "470fe3126fc0"
down_revision: str | None = "440853283436"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "telegram_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "telegram_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True)
    # ### end Alembic commands ###
