"""add id field to potential user table

Revision ID: e4798976bd79
Revises: 5434c5fc5066
Create Date: 2024-01-04 21:20:05.067718

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e4798976bd79"
down_revision: Union[str, None] = "5434c5fc5066"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "potential_user",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
    )
    # set email as not unique and not primary key
    op.alter_column("potential_user", "email", nullable=False, primary_key=False, unique=False)
    op.drop_constraint("potential_user_pkey", "potential_user", type_="primary")
    op.create_primary_key("potential_user_pkey", "potential_user", ["id"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("potential_user", "id")
    # ### end Alembic commands ###
