"""rename participant to user

Revision ID: 440853283436
Revises: ae811bbde3f1
Create Date: 2024-03-24 18:21:18.119244

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "440853283436"
down_revision: str | None = "ae811bbde3f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("participant", "user")
    op.drop_constraint("booking_user_id_fkey", "booking", type_="foreignkey")
    op.create_foreign_key(None, "booking", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "booking", type_="foreignkey")
    op.create_foreign_key("booking_user_id_fkey", "booking", "participant", ["user_id"], ["id"])
    op.rename_table("user", "participant")
    # ### end Alembic commands ###
