"""add is_using_music_room to user

Revision ID: 4e995f48804a
Revises: 470fe3126fc0
Create Date: 2026-09-01 22:40:11.957199

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e995f48804a"
down_revision: str | None = "470fe3126fc0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_using_music_room", sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_using_music_room")
    # ### end Alembic commands ###
